---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sorter
  name: deployment-sorter
  namespace: sorter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sorter
  template:
    metadata:
      labels:
        app: sorter
      name: sorter-pod
    spec:
      containers:
      - image: dnbl/sorter:latest
        imagePullPolicy: Always
        name: sorter
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sorter
  name: svc-sorter
  namespace: sorter
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sorter
  type: NodePort