# Default values for sorter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
buildnumber: "not-set"
environment: "not-set"

image:
  repository: dnbl/sorter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: NodePort
  nodeport: 32223
  targetport: 3000
  port: 80
