apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sorter
  name: 'deploy-sorter-'{{.Values.environment}}
  namespace: 'sorter-'{{.Values.environment}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: sorter
  template:
    metadata:
      annotations:
        buildnumber: {{.Values.buildnumber}}
      labels:
        app: sorter
      name: sorter-pod
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: sorter
          ports:
            - containerPort: 3000
