apiVersion: v1
kind: Service
metadata:
  labels:
    app: sorter
  name: svc-sorter
  namespace: sorter
spec:
  ports:
    - nodePort: {{.Values.service.nodeport}}
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.targetport}}
  selector:
    app: sorter
  type: {{.Values.service.type}}
